baseURL = "https://berkaycubuk.com/"
languageCode = "en-us"
title = "Berkay Çubuk"
enableEmoji = true

#[[menus.main]]
#  name = 'Services'
#  url = '/services'
#  weight = 1
[[menus.main]]
  name = 'Work'
  url = '/work'
  weight = 2
[[menus.main]]
  name = 'Blog'
  url = '/blog'
  weight = 3
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 4
#[[menus.main]]
#  name = 'Contact'
#  url = '/contact'
#  weight = 5

[params]
  description = "I solve problems"
  linkedin = 'https://www.linkedin.com/in/berkaycubuk/'
  twitter = 'https://twitter.com/brkycubuk'
  youtube = 'https://www.youtube.com/@berkaycubuk'
  github = 'https://github.com/berkaycubuk'
